### ISSUE TITLE
제출문서 작성

### ISSUE THREAD

**Issue by gracehkpark** [mcyirock/GangReungProject#16]
[별첨1]참가신청서_헬로강원 (완료)
[별첨2]개인정보수집이용동의서_헬로강원(완료)
[별첨3]응모아이디어제3자공개공유동의서_헬로강원(완료)
[별첨4]개발계획서_헬로강원(작성중)
[별첨5]서비스소개_헬로강원(작성중)

**Comment by mcyirock** [comment]
1. 엡 스크린 샷과 설명, 그리고 해당화면의 추가적 기능 구현 계획을 서술.
2. 다국어 버전 출시 비전에 관해 설명 (한국어, 중국어, etc)
3. 강원도 api에 있는 다양한 자료와 호환성 그러므로 확장성을 강조 -> 똑같은 자료구조를 가지고 있음
4. 길찾기와 택시연동

외에 기타 의견을 제시해 주세요.

**Comment by mcyirock** [comment]
강원도 강릉 팀임을 강조.

**Comment by gracehkpark** [comment]
넵~ 알겠습니다~ㅎㅎ

**Comment by mcyirock** [comment]
작성완료 했습니다
