### ISSUE TITLE
레이아웃 리소스 관련

### ISSUE THREAD

**Issue by gracehkpark** [mcyirock/GangReungProject#20]
요청1. Rating bar에서 별 색깔 변경
[list_item.xml] 파일에서 ratingbar 속성에 추가 부탁드립니다.
android:progressTint="#88f99a53"

요청 2. 연꽃 아이콘 변경
![ic_buddhism](https://cloud.githubusercontent.com/assets/6822904/11455189/b73ba308-9693-11e5-9702-1acfda82d69a.jpg)

요청 3. Cardview Tip에서 영어 글씨 두껍게
[recycler_view_card_item.xml] 파일에서 id가 eng_expression 텍스트뷰에 속성 추가 부탁드립니다.
android:textStyle="bold" 

요청 4. Cardview에서 콘텐츠 합치기 (같은 주제끼리 합치기)
Purchase Ticket
-티켓 어디서 사요
-티켓 얼마에요?

Buy Stuff
-얼마에요
-너무 비싸요. 좀 깍아주세요.
-면세되나요?

Taxi

**Comment by mcyirock** [comment]
Solved and included in beta 1.1
