### ISSUE TITLE
내생각 GUI

### ISSUE THREAD

**Issue by CoolShaun** [mcyirock/GangReungProject#3]
다이닝테이블을 대충 급하게 고쳐서 - 이건 개념입니다. 시간이없기때문에 ㅋ
![gui](https://cloud.githubusercontent.com/assets/15794958/11084530/cb9e2a90-887f-11e5-85c8-9d528a4caa88.png)

**Comment by mcyirock** [comment]
아주 괜찮다고 생각됩니다.
이렇게 가면 인터넷 커넥션이 꼭 필요합니다.
세부사항 페이지을 더하면 틀은 완성이 된듯합니다

**Comment by CoolShaun** [comment]
네 일단 틀을 잡고 세부사항에서 디자인이라든지 유저편의에 기반한 접근성을 생각해보면될듯합니다요.
일단 시간이없잖아요. ㅋㅋㅋ

**Comment by gracehkpark** [comment]
서울데이트팝처럼 지도로 들어가는 화면은 이런식으로 지구로 나눠서 구현 가능할 것 같아요.

![default](https://cloud.githubusercontent.com/assets/6822904/11084940/a595ac7e-8884-11e5-9903-08b1886a3d4b.PNG)
![2](https://cloud.githubusercontent.com/assets/6822904/11084942/a72cb744-8884-11e5-8544-ac7e98ce4a5b.PNG)

**Comment by mcyirock** [comment]
좋은 레퍼런스라고 봅니다!

**Comment by gracehkpark** [comment]
![3bb5c28669372e6fcb43b970984265a5](https://cloud.githubusercontent.com/assets/6822904/11137007/3716478a-89f7-11e5-8faf-6f39be599040.jpg)
![gangneungsine-map](https://cloud.githubusercontent.com/assets/6822904/11137009/398f8cb0-89f7-11e5-8351-15d96af4a0dd.png)

**Comment by CoolShaun** [comment]
와우~! 언제이런걸 다했데요? 디자이너가 좀 이쁘게 하면 지난번 보여줬던 서울데이트앱처럼 깔끔하게 될듯한데요?

**Comment by gracehkpark** [comment]
아~ 저거는 구글링을 통해 찾았습니다^^ 저걸 토대로 하면 될 것 같아요 ㅎㅎ 주말에 작업을 해볼게요

**Comment by gracehkpark** [comment]
배경화면 위에 좌표로 버튼 생성하기

http://www.androidside.com/bbs/board.php?bo_table=B49&wr_id=148230

**Comment by gracehkpark** [comment]
http://blog.naver.com/springrain85/220486305927

**Comment by gracehkpark** [comment]
Spinner 라이브러리 : https://github.com/rajasharan/SearchableSpinner

**Comment by gracehkpark** [comment]
강원도 18개 시/군 행정구역으로 다시 이미지 작업 예정

**Comment by mcyirock** [comment]
GUI 확정 이슈 내립니다.
