### ISSUE TITLE
런처 아이콘

### ISSUE THREAD

**Issue by mcyirock** [mcyirock/GangReungProject#4]
![web_hi_res_512](https://cloud.githubusercontent.com/assets/6494948/11109030/aaf39144-892f-11e5-84fa-f7c2fd126bee.png)
코멘트 부탁해요.

**Comment by CoolShaun** [comment]
GR은 무슨약자에요?

**Comment by gracehkpark** [comment]
강릉~?

**Comment by mcyirock** [comment]
맞습니다.^^

**Comment by CoolShaun** [comment]
강릉의 공식 영문명은 Gang Neung 아닌가요?

**Comment by mcyirock** [comment]
굿포인트

**Comment by CoolShaun** [comment]
런처이름은 왠지 공무원분들께서 보기좋은걸로 가는게좋지않을까요?
강릉만 있는걸로 가면 솔향강릉 요런거도 넣고....소나무그림을 베이스로 런처만들어도좋고...강원도전체를 할꺼면 강원도만의 특색있는걸로 가면좋을듯합니다.

**Comment by gracehkpark** [comment]
오늘 서울 올라가서 디자인과 친구를 만나니 그 친구한테 살짜쿵 부탁을 해보겠습니다.
강릉을 잘 나타내고, 공무원들/외국인들이 좋아할만한 심플한 디자인과 앱 전체적인 색상을 좀 뽑아달라고 해볼게요.^^

**Comment by gracehkpark** [comment]
앱 디자인 도와줬었던 경험이 있어서 믿을만합니다 :)

![02](https://cloud.githubusercontent.com/assets/6822904/11136918/43442122-89f6-11e5-9829-f06af6f173fa.jpg)

**Comment by CoolShaun** [comment]
와우 좋네요~! 색감만 좀 더 밝게하면 좋을꺼같은데요?

**Comment by gracehkpark** [comment]
네~ 저거는 예전에 했던 앱 예시에요! :)

**Comment by mcyirock** [comment]
훌륭합니다!

**Comment by CoolShaun** [comment]
역시! 한번 해본사람은 틀리네요~! 앱의 전체적인 색은 강릉에 바닷가가많고, 소나무가 강릉상징이니, 바다색같은 파란색위주와 소나무를 상징하는 연두색?(녹색) 위주로 파스텔톤으로 가면 좋을듯합니다.

**Comment by gracehkpark** [comment]
넵~ 참고하겠습니다!

**Comment by mcyirock** [comment]
그레이스님이 보내주신 시안의 hdpi, mdpi, xhdpi, xxhdpi, xxxhdpi 리사이즈를 해서 적용하면 이 이슈는 클로즈 하겠습니다.

**Comment by gracehkpark** [comment]
작업파일은 오늘 밤에 올리겠습니다~ :)

**Comment by gracehkpark** [comment]
녹색: #99cc33
노랑: #ffc44d
주황: #f99a53
회색: #afafaf
타이틀: #444444
