### ISSUE TITLE
Tip 콘텐츠

### ISSUE THREAD

**Issue by gracehkpark** [mcyirock/GangReungProject#5]
외국인에게 Tip을 주는 콘텐츠를 어떻게 제작하면 좋을까요?
직접 제작해서 올리는 방식이 있고, 어디선가 받아와서 올리는 방법이 있을 것 같네요.

**Comment by gracehkpark** [comment]
페이스북 Peeps in Gangneung 여기 페이지에서 본 것 중에 이런 콘텐츠도 있긴했습니다.
![korean expression](https://cloud.githubusercontent.com/assets/6822904/11327267/cfceef3a-91c3-11e5-9a88-e648df40d06f.jpg)
![korean expression2](https://cloud.githubusercontent.com/assets/6822904/11327268/d0c03782-91c3-11e5-9f12-bbca19ec698a.jpg)
![korean expression3](https://cloud.githubusercontent.com/assets/6822904/11327269/d31c58ee-91c3-11e5-9f0f-e35376ea585c.jpg)

**Comment by gracehkpark** [comment]
음식점, 교통, 숙박, 쇼핑

참고 (http://english.visitkorea.or.kr/enu/AK/AK_EN_1_5_13_3.jsp)

**Comment by CoolShaun** [comment]
식당

Do you have an English menu?
Yeong-eo menyu-ga iseoyo?

I`d llike to place an order.
Jumun-hal-geyo.

Please recommend the most delicious food in this restaurant.
Ejib-eseo gajang masinneun emsig-el choochun-hae juseyo.

How much is this?
eolma-yeyo?

Can I have one more rice bowl please?
bab hangongi deo juseyo

It`s delicious!
masisseoyo.

Can you please remove (specific ingredient) in this food?
Emsig-eseo (specific ingredient) bbae juseoyo.

Onion (yangpa), Garlic(maneul), beef(sogogi), pork(deojigogi), red pepper(gochugaru)

Less spicy
(deol mabgae haejuseyo)
Less salt
(singubge haejuseyo)

More spicy
(mabgae haejuseyo)
More salt
(jjagae haejuseyo)


쇼핑

How much is this?
eolma-yeyo

Can I try it on?
ibebwa-do dwaeyo

(Too) Expensive.
(neomu) bissayo

Please give me some discount.
jom kkakka-juseyo

Do you have big size?
keun size itnayo

Do you have small size?
jjac-en size itnayo

It`s (too) tight.
(neomu) ggyeyo

It`s (too) loose.
(neomu) hul-lung-haeyo.

관광지

Where is the toilet?
hwajangsil ediyeyo

Where can I buy the admission ticket?
Ipjanggwoneul eodiseo sayo

Could you please help me take a picture?
Sajin jjigeo-juseyo

How long would it take by walking?
Georeo-seo myeot bun-ina geol-lyeyo

How long would it take by taxi?
taxi tamyeon eolmana geolinayo

How long would it take by bus?
bus tamyeon eolmana geolinayo

How long would it take by subway?
jihacheol tamyeon eolmana geolinayo

How can I go (specific place)?
(specific place)-e auddeoke ganayo?

숙박

I booked at this hotel.
yeogi yeoyac haeseoyo.

Would you show me the room?
bang jom boyeo juseyo

I want to stay a day longer.
harubam deo iteulsu itnayo

Does the room have a shower and bathtub?
shower mit yokjo siseol-ie itnayo

Please gvie me a wake-up call at () tomorrow morning.
a-chim ()si-e ggawo-juseyo.

This room is too dirty, Please have it cleaned.
e-bangeun nemu deoruwoyo, chungso jom haejuseyo

This room is too hot(cold).
e-bangeun nemu deowoyo (chuwoyo).

I didn`t make a reservation. Are there any vacancies?
Bin-bang it nayo

**Comment by gracehkpark** [comment]
[Purchase Tickets]
- Where can I buy the admission ticket?
- 티켓 어디서 사요?
- Ticket Eo di seo sa yo?

- How much is the admission fee/ ticket?
- 입장료(티켓) 얼마예요?
- Ticket eol ma ye yo?

[Buy stuffs]
- How much is this?
- 얼마예요?
- Eol ma ye yo?

- This is too expensive. Please give me some discount.
- 너무 비싸요. 좀 깎아주세요.
- Neo mu bi ssa yo. jom kka kka ju se yo.

- Is this tax free?
- 면세 되나요?
- Tax-free de na yo?

[Taxi]
- Sir, I would like to go to this place.
- 기사님. 여기로 가주세요.
- Gi sa nim, yeo gi jom ga ju se yo.

**Comment by mcyirock** [comment]
카드뷰 연속으로 구현
